<a href="https://colab.research.google.com/github/zdac040/Dissertation/blob/master/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# https://www.tensorflow.org/tutorials/quickstart/beginner

import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import layers

import pandas as pd
import numpy as np

from google.colab import files

In [ ]:
print(tf.__version__)

2.3.0


In [ ]:
f = files.upload()

colNS = ['RAW', 'EMG', 'BINARY'] 
dataNS = pd.read_excel("NULLSIGNAL.xlsx", names=colNS) 

colMF = ['RAW', 'EMG', 'BINARY'] 
dataMF = pd.read_excel("MIDDLEFINGER.xlsx", names=colMF) 

colP = ['RAW', 'EMG', 'BINARY'] 
dataP = pd.read_excel("PUNCH.xlsx", names=colP) 

colC = ['RAW', 'EMG', 'BINARY'] 
dataC = pd.read_excel("CONTRACTION.xlsx", names=colC) 

In [ ]:
num_rows = dataNS.shape[0]

print(num_rows)

239


In [ ]:
# windows size of 4 rows to transform the table
win_size = 4
trans_table_ns = np.zeros((num_rows-win_size+1,2*win_size+1)) #it creates object of type array

for i in range(num_rows-win_size+1):
  cur_slice = dataNS.iloc[i:i+win_size,:]
  raw_slice = np.array(cur_slice['RAW'])
  emg_slice = np.array(cur_slice['EMG'])
  classification = np.max(cur_slice['BINARY'])
  trans_table_ns[i,:] = np.append(np.concatenate((raw_slice,emg_slice)),classification)

print(raw_slice)
print(emg_slice)
print(classification)
print(trans_table_ns)

[770 770 770 770]
[35 35 35 35]
0
[[769. 771. 770. ...  48.  35.   0.]
 [771. 770. 768. ...  35.  41.   0.]
 [770. 768. 770. ...  41.  47.   0.]
 ...
 [770. 770. 770. ...  35.  35.   0.]
 [770. 770. 770. ...  35.  35.   0.]
 [770. 770. 770. ...  35.  35.   0.]]


In [ ]:
num_rows = dataMF.shape[0]

print(num_rows)

239


In [ ]:
win_size = 4
trans_table_mf = np.zeros((num_rows-win_size+1,2*win_size+1))

for i in range(num_rows-win_size+1):
  cur_slice = dataMF.iloc[i:i+win_size,:]
  raw_slice = np.array(cur_slice['RAW'])
  emg_slice = np.array(cur_slice['EMG'])
  classification = np.max(cur_slice['BINARY'])
  trans_table_mf[i,:] = np.append(np.concatenate((raw_slice,emg_slice)),classification)

print(trans_table_mf)

[[772. 774. 776. ... 580.  96.   1.]
 [774. 776. 769. ...  96. 124.   1.]
 [776. 769. 767. ... 124. 224.   1.]
 ...
 [641. 641. 641. ...  86.  86.   0.]
 [641. 641. 641. ...  86.  86.   0.]
 [641. 641. 641. ...  86.  86.   0.]]


In [ ]:
num_rows = dataP.shape[0]

print(num_rows)

239


In [ ]:
win_size = 4
trans_table_p = np.zeros((num_rows-win_size+1,2*win_size+1))

for i in range(num_rows-win_size+1):
  cur_slice = dataP.iloc[i:i+win_size,:]
  raw_slice = np.array(cur_slice['RAW'])
  emg_slice = np.array(cur_slice['EMG'])
  classification = np.max(cur_slice['BINARY'])
  trans_table_p[i,:] = np.append(np.concatenate((raw_slice,emg_slice)),classification)

print(trans_table_p)

[[ 770.  772.  773. ...  154. 1023.    2.]
 [ 772.  773.  732. ... 1023.  491.    2.]
 [ 773.  732.  747. ...  491. 1023.    2.]
 ...
 [ 768.  768.  768. ...  355.  177.    2.]
 [ 768.  768.  768. ...  177.  177.    2.]
 [ 768.  768.  768. ...  177.  177.    2.]]


In [ ]:
num_rows = dataC.shape[0]

print(num_rows)

239


In [ ]:
win_size = 4
trans_table_c = np.zeros((num_rows-win_size+1,2*win_size+1))

for i in range(num_rows-win_size+1):
  cur_slice = dataC.iloc[i:i+win_size,:]
  raw_slice = np.array(cur_slice['RAW'])
  emg_slice = np.array(cur_slice['EMG'])
  classification = np.max(cur_slice['BINARY'])
  trans_table_c[i,:] = np.append(np.concatenate((raw_slice,emg_slice)),classification)

print(trans_table_c)

[[ 767.  767.  769. ...   41.   40.    0.]
 [ 767.  769.  769. ...   40.  141.    0.]
 [ 769.  769.  718. ...  141.    3.    0.]
 ...
 [ 763.  763.  763. ...  235. 1023.    3.]
 [ 763.  763.  763. ... 1023. 1023.    3.]
 [ 763.  763.  763. ... 1023. 1023.    3.]]


In [ ]:
# xs (the input to the classifier) are the first n-1 columns, the ys are the last one
xns = trans_table_ns[:,:-1]
yns = trans_table_ns[:,-1]

# normalization of the the inputs so that they are centered at 0

xns = (xns-512)/1024

print(xns)
print(yns)

[[ 0.25097656  0.25292969  0.25195312 ... -0.45507812 -0.453125
  -0.46582031]
 [ 0.25292969  0.25195312  0.25       ... -0.453125   -0.46582031
  -0.45996094]
 [ 0.25195312  0.25        0.25195312 ... -0.46582031 -0.45996094
  -0.45410156]
 ...
 [ 0.25195312  0.25195312  0.25195312 ... -0.46582031 -0.46582031
  -0.46582031]
 [ 0.25195312  0.25195312  0.25195312 ... -0.46582031 -0.46582031
  -0.46582031]
 [ 0.25195312  0.25195312  0.25195312 ... -0.46582031 -0.46582031
  -0.46582031]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [ ]:
xmf = trans_table_mf[:,:-1]
ymf = trans_table_mf[:,-1]

xmf = (xmf-512)/1024

print(xmf)
print(ymf)

[[ 0.25390625  0.25585938  0.2578125  ... -0.39648438  0.06640625
  -0.40625   ]
 [ 0.25585938  0.2578125   0.25097656 ...  0.06640625 -0.40625
  -0.37890625]
 [ 0.2578125   0.25097656  0.24902344 ... -0.40625    -0.37890625
  -0.28125   ]
 ...
 [ 0.12597656  0.12597656  0.12597656 ... -0.41601562 -0.41601562
  -0.41601562]
 [ 0.12597656  0.12597656  0.12597656 ... -0.41601562 -0.41601562
  -0.41601562]
 [ 0.12597656  0.12597656  0.12597656 ... -0.41601562 -0.41601562
  -0.41601562]]
[1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1.
 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 0. 0. 1. 1. 1. 1.


In [ ]:
xp = trans_table_p[:,:-1]
yp = trans_table_p[:,-1]

xp = (xp-512)/1024

print(xp)
print(yp)

[[ 0.25195312  0.25390625  0.25488281 ... -0.27148438 -0.34960938
   0.49902344]
 [ 0.25390625  0.25488281  0.21484375 ... -0.34960938  0.49902344
  -0.02050781]
 [ 0.25488281  0.21484375  0.22949219 ...  0.49902344 -0.02050781
   0.49902344]
 ...
 [ 0.25        0.25        0.25       ... -0.43652344 -0.15332031
  -0.32714844]
 [ 0.25        0.25        0.25       ... -0.15332031 -0.32714844
  -0.32714844]
 [ 0.25        0.25        0.25       ... -0.32714844 -0.32714844
  -0.32714844]]
[2. 2. 2. 2. 0. 0. 2. 2. 2. 2. 0. 2. 2. 2. 2. 2. 2. 2. 2. 0. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 0. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 2. 2. 2. 2. 0. 2. 2. 2.
 2. 0. 0. 0. 0. 2. 2. 2. 2. 2. 2. 2. 2. 0. 0. 0. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 2. 2. 2. 2. 2. 

In [ ]:
xc = trans_table_c[:,:-1]
yc = trans_table_c[:,-1]

xc = (xc-512)/1024

print(xc)
print(yc)

[[ 0.24902344  0.24902344  0.25097656 ... -0.43945312 -0.45996094
  -0.4609375 ]
 [ 0.24902344  0.25097656  0.25097656 ... -0.45996094 -0.4609375
  -0.36230469]
 [ 0.25097656  0.25097656  0.20117188 ... -0.4609375  -0.36230469
  -0.49707031]
 ...
 [ 0.24511719  0.24511719  0.24511719 ... -0.23339844 -0.27050781
   0.49902344]
 [ 0.24511719  0.24511719  0.24511719 ... -0.27050781  0.49902344
   0.49902344]
 [ 0.24511719  0.24511719  0.24511719 ...  0.49902344  0.49902344
   0.49902344]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 3. 3. 3. 3. 0. 0. 0. 0. 3. 3. 3. 3. 0. 0. 0.
 3. 3. 3. 3. 0. 0. 3. 3. 3. 3. 0. 3. 3. 3. 3. 0. 0. 3. 3. 3. 3. 0. 3. 3.
 3. 3. 0. 3. 3. 3. 3. 0. 3. 3. 3. 3. 0. 3. 3. 3. 3. 0. 0. 3. 3. 3. 3. 0.
 3. 3. 3. 3. 0. 3. 3. 3. 3. 0. 3. 3. 3. 3. 0. 3. 3. 3. 3. 0. 3. 3. 3. 3.
 0. 3. 3. 3. 3. 0. 3. 3. 3. 3. 0. 0. 3. 3. 3. 3. 0. 3. 3. 3. 3. 0. 3. 3.
 3. 3. 0. 0. 3. 3. 3. 3. 0. 3. 3. 3. 3. 0. 0. 3. 3. 3. 3. 0. 3. 3. 3. 3.
 0. 0. 3. 3. 3. 3. 0. 3. 3. 3. 3. 0. 3. 3. 3. 3. 0. 3. 3. 3. 3. 0. 3. 3

In [ ]:
x = np.concatenate((xns, xmf, xp, xc))
y = np.concatenate((yns, ymf, yp, yc))


In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [ ]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(150, activation='relu', input_shape=(2*win_size,)),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(4)
])

In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.04771198, -0.00631762,  0.12232989, -0.00596632]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.23417848, 0.24407558, 0.27758452, 0.24416134]], dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

1.4516717

In [ ]:
model.compile(optimizer='adam',
              loss= loss_fn,
              metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=60)

Epoch 1/60
21/21 [==============================] - 0s 1ms/step - loss: 0.6644 - accuracy: 0.7015
Epoch 2/60
21/21 [==============================] - 0s 1ms/step - loss: 0.6665 - accuracy: 0.7106
Epoch 3/60
21/21 [==============================] - 0s 1ms/step - loss: 0.6739 - accuracy: 0.6955
Epoch 4/60
21/21 [==============================] - 0s 2ms/step - loss: 0.6632 - accuracy: 0.7000
Epoch 5/60
21/21 [==============================] - 0s 1ms/step - loss: 0.6726 - accuracy: 0.6955
Epoch 6/60
21/21 [==============================] - 0s 2ms/step - loss: 0.6520 - accuracy: 0.7076
Epoch 7/60
21/21 [==============================] - 0s 1ms/step - loss: 0.6638 - accuracy: 0.7000
Epoch 8/60
21/21 [==============================] - 0s 1ms/step - loss: 0.6543 - accuracy: 0.6879
Epoch 9/60
21/21 [==============================] - 0s 1ms/step - loss: 0.6663 - accuracy: 0.6970
Epoch 10/60
21/21 [==============================] - 0s 1ms/step - loss: 0.6481 - accuracy: 0.7091
Epoch 11/60
21/21 [

In [ ]:
model.evaluate(x_test,  y_test, verbose=2)

9/9 - 0s - loss: 0.5748 - accuracy: 0.7641


[0.5748055577278137, 0.76408451795578]

In [ ]:
# https://stackoverflow.com/questions/52753846/error-in-load-a-model-saved-by-callbakcs-modelcheckpoint-in-keras 

from keras.models import load_model

model.save('model.h5') 

In [ ]:
#https://www.tensorflow.org/lite/convert/python_api

# # Convert the model.
# converter = tf.lite.TFLiteConverter.from_keras_model(model)
# tflite_model = converter.convert()

# # Save the TF Lite model.
# with tf.io.gfile.GFile('model.tflite', 'wb') as f:
#   f.write(tflite_model)